server:
  port: 8765
  
info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
 

zuul:
  prefix: /api
  routes:
    user:
      path: /user/**
      serviceId: USER-SERVICE
    review:
      path: /reviews/**
      serviceId: REVIEW-SERVICE
    composite:
      path: /composite/**
      serviceId: COMPOSITE-SERVICE 
      
  host:
    socket-timeout-millis: 600000  
    connect-timeout-millis: 600000   
    
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000 
